dataset: 'celeba'
datapath: '/home/cx/LINMUX/Datasets/CelebA'
model_type: bengin
num_classes: 8
batch_size: 128
epochs: 100
save_dir: './checkpoint'
poison_ratio: 0.2
device: 'cuda'
target_class: 7
noise_alpha: 0.3
height: 64
width: 64
EPSILON: 1e-7
init_cost: 1e-3
cost_multiplier: 2
atk_succ_threshold: 98
early_stop: True
early_stop_threshold: 99.0
early_stop_patience: 25
patience: 5
to_file: True