dataset: 'cifar'
datapath: '/home/cx/LINMUX/Datasets/cifar-10-batches-py'
model_type: bengin
num_classes: 10
batch_size: 128
epochs: 300
save_dir: './checkpoint'
poison_ratio: 0.2
device: 'cuda'
target_class: 7
noise_alpha: 0.3
EPSILON: 1e-7
init_cost: 1e-3
cost_multiplier: 2
atk_succ_threshold: 98
n_sample: 100
n_test: 100
test_rounds: 10
detection_boundary: 0.2