dataset: 'imagenet'
datapath: '/home/cx/LINMUX/Datasets/ImageNet-12-new'
model_type: bengin
num_classes: 12
batch_size: 64
epochs: 200
save_dir: './checkpoint'
poison_ratio: 0.2
device: 'cuda'
target_class: 7
noise_alpha: 0.3
height: 224
width: 224
EPSILON: 1e-7
init_cost: 1e-3
cost_multiplier: 2
atk_succ_threshold: 98
early_stop: True
early_stop_threshold: 99.0
early_stop_patience: 25
patience: 5
to_file: True
